services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_api_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/1
      DBUSER: postgres
      DBPASS: postgres
      DBHOST: db
      RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/1
      DBUSER: postgres
      DBPASS: postgres
      DBHOST: db
      RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle

volumes:
  postgres_data:
  bundle_cache:
